#!/usr/bin/python3
# Get admin password

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
    action_get,
    config,
    log,
)

from charmhelpers.core import unitdata

kv = unitdata.kv()
if kv.get('grafana.admin_password'):
    # print('Admin password: {}'.format(kv.get('grafana.admin_password')))
    passwd = kv.get('grafana.admin_password')
elif config('admin_password'):
    passwd = config('admin_password')
    # print('Admin password: {}'.format(config('admin_password')))
else:
    action_fail('ERROR! Unable to retrieve password.')
    exit(0)

action_set({"password": passwd})
