#!/usr/bin/python3
# Get admin password

from grafana_utils import get_admin_password

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
)

passwd = get_admin_password()

if passwd is not None:
    action_set({"password": passwd})
else:
    action_fail('ERROR! Unable to retrieve password.')
    exit(0)

